-- Switch to the pluggable database
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Drop the user if it already exists (optional for repeatability)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER myapp_user CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01918 THEN -- user does not exist
            RAISE;
        END IF;
END;
/

-- Create a new user (schema)
CREATE USER myapp_user IDENTIFIED BY myapp_password;

-- Grant privileges to the user
GRANT CONNECT, RESOURCE TO myapp_user;
GRANT UNLIMITED TABLESPACE TO myapp_user;

-- Set current schema for table creation
ALTER SESSION SET CURRENT_SCHEMA = myapp_user;

-- Create a simple 'users' table
CREATE TABLE users
(
    user_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR2(50)  NOT NULL,
    email      VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create an 'orders' table with foreign key to users
CREATE TABLE orders
(
    order_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    NUMBER NOT NULL,
    amount     NUMBER(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);
