package mb.oauth2authorizationserver.config.jpa;

import java.io.Serial;
import java.io.Serializable;

/**
 * Settings for {@link OracleInClauseInspector}.
 * <p>
 * Use this record when a new Oracle list type or limit is needed instead of changing inspector logic.
 *
 * @param maxParameterCount              maximum bind parameters in a single {@code IN} list before rewriting starts
 * @param oracleFunctionMaxArgumentCount maximum bind parameters passed to each {@code sys.odcinumberlist(...)} call
 * @param oracleTableFunction            Oracle collection function, e.g. {@code sys.odcinumberlist} or {@code sys.odcivarchar2list}
 * @param requireColumnExpression        when {@code true}, rewrite only if a column expression exists before {@code IN}
 * @param enabled                        when {@code false}, SQL is returned unchanged
 */
public record OracleInClauseRewriteConfig(int maxParameterCount,
                                          int oracleFunctionMaxArgumentCount,
                                          String oracleTableFunction,
                                          boolean requireColumnExpression,
                                          boolean enabled) implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    public OracleInClauseRewriteConfig {
        if (maxParameterCount < 1) {
            throw new IllegalArgumentException("maxParameterCount must be at least 1");
        }
        if (oracleFunctionMaxArgumentCount < 1) {
            throw new IllegalArgumentException("oracleFunctionMaxArgumentCount must be at least 1");
        }
        if (oracleTableFunction == null || oracleTableFunction.isBlank()) {
            throw new IllegalArgumentException("oracleTableFunction must not be blank");
        }
    }

    /**
     * Default settings for numeric {@code IN} lists generated by Hibernate.
     */
    public static OracleInClauseRewriteConfig defaults() {
        return new OracleInClauseRewriteConfig(999, 999, "sys.odcinumberlist", true, true);
    }

    /**
     * Settings for string {@code IN} lists.
     */
    public static OracleInClauseRewriteConfig forStrings() {
        return new OracleInClauseRewriteConfig(999, 999, "sys.odcivarchar2list", true, true);
    }
}
