package mb.oauth2authorizationserver.config.jpa;

import org.hibernate.resource.jdbc.spi.StatementInspector;

import java.io.Serial;

/**
 * Rewrites large Hibernate {@code IN (? , ? , ...)} clauses before they are sent to Oracle.
 * <p>
 * Oracle rejects {@code IN} lists with more than 1000 expressions. When a clause exceeds the configured
 * limit, it is converted to use an Oracle table function such as {@code sys.odcinumberlist}.
 * <p>
 * Safety rules:
 * <ul>
 *   <li>Only pure placeholder lists like {@code IN (?, ?, ?)} are rewritten</li>
 *   <li>Subqueries, literals, and already rewritten clauses are left unchanged</li>
 *   <li>When parsing is uncertain, the original SQL is preserved</li>
 * </ul>
 * <p>
 * Example input:
 * {@code SELECT * FROM product_asset WHERE product_id IN (?, ?, ... 1000 times ...)}
 * <p>
 * Example output:
 * {@code SELECT * FROM product_asset WHERE product_id IN (SELECT column_value FROM TABLE(sys.odcinumberlist(?, ?, ...)))}
 */
public class OracleInClauseInspector implements StatementInspector {

    @Serial
    private static final long serialVersionUID = 1L;

    private final OracleInClauseRewriteConfig config;

    public OracleInClauseInspector() {
        this(OracleInClauseRewriteConfig.defaults());
    }

    public OracleInClauseInspector(OracleInClauseRewriteConfig config) {
        this.config = config;
    }

    /**
     * Inspects SQL generated by Hibernate and rewrites oversized {@code IN} clauses.
     * <p>
     * Clauses within the configured parameter limit are returned unchanged.
     *
     * @param sql SQL statement before execution
     * @return the original SQL, or SQL with large {@code IN} clauses rewritten for Oracle
     * {@code @example} {@code inspect("... WHERE product_id IN (?,?,...)")} rewrites only when the list exceeds the configured limit
     */
    @Override
    public String inspect(String sql) {
        if (sql == null || !config.enabled() || !sql.toLowerCase().contains("in")) {
            return sql;
        }

        StringBuilder result = new StringBuilder(sql.length());
        int cursor = 0;

        while (cursor < sql.length()) {
            InKeywordMatch keyword = findNextInKeyword(sql, cursor);
            if (keyword == null) {
                result.append(sql, cursor, sql.length());
                cursor = sql.length();
            } else {
                InClauseMatch match = parseInClause(sql, keyword);
                if (match == null) {
                    result.append(sql, cursor, keyword.start() + 1);
                    cursor = keyword.start() + 1;
                } else {
                    result.append(sql, cursor, match.keywordStart());

                    if (shouldRewrite(sql, match)) {
                        result.append(sql, match.keywordStart(), match.listOpenParen())
                                .append("(SELECT column_value FROM TABLE(")
                                .append(config.oracleTableFunction())
                                .append("(")
                                .append(generateQuestionMarks(match.paramCount()))
                                .append(")))");
                    } else {
                        result.append(sql, match.keywordStart(), match.end());
                    }

                    cursor = match.end();
                }
            }
        }

        return result.toString();
    }

    private boolean shouldRewrite(String sql, InClauseMatch match) {
        if (!match.placeholderList()) {
            return false;
        }
        if (match.paramCount() <= config.maxParameterCount()) {
            return false;
        }
        return !config.requireColumnExpression() || !extractColumnExpression(sql, match.keywordStart()).isEmpty();
    }

    /**
     * Finds the next {@code IN} or {@code NOT IN} keyword in the SQL.
     *
     * @param sql  SQL text to scan
     * @param from index to start searching from
     * @return keyword position details, or {@code null} if not found
     * {@code @example} {@code findNextInKeyword("WHERE product_id NOT IN (?)", 0)} matches {@code NOT IN}
     */
    private static InKeywordMatch findNextInKeyword(String sql, int from) {
        for (int index = from; index < sql.length(); index++) {
            InKeywordMatch notInKeyword = readNotInKeyword(sql, index);
            if (notInKeyword != null) {
                return notInKeyword;
            }
            InKeywordMatch inKeyword = readInKeyword(sql, index);
            if (inKeyword != null) {
                return inKeyword;
            }
        }
        return null;
    }

    /**
     * Reads a standalone {@code NOT IN} keyword at the given index.
     */
    private static InKeywordMatch readNotInKeyword(String sql, int index) {
        if (regionMatchesIgnoreCase(sql, index, "not")) {
            return null;
        }
        int inStart = skipWhitespace(sql, index + 3);
        if (regionMatchesIgnoreCase(sql, inStart, "in")) {
            return null;
        }
        if (hasKeywordBoundaryBefore(sql, index)) {
            return null;
        }
        int keywordEnd = inStart + 2;
        if (hasKeywordBoundaryAfter(sql, keywordEnd)) {
            return null;
        }
        return new InKeywordMatch(index, keywordEnd);
    }

    /**
     * Reads a standalone {@code IN} keyword at the given index.
     */
    private static InKeywordMatch readInKeyword(String sql, int index) {
        if (regionMatchesIgnoreCase(sql, index, "in")) {
            return null;
        }
        if (hasKeywordBoundaryBefore(sql, index)) {
            return null;
        }
        if (hasKeywordBoundaryAfter(sql, index + 2)) {
            return null;
        }
        return new InKeywordMatch(index, index + 2);
    }

    /**
     * Parses an {@code IN}/{@code NOT IN} clause and classifies whether it is rewriteable.
     * <p>
     * Returns a non-placeholder match for subqueries and already rewritten clauses so they are copied unchanged.
     */
    private InClauseMatch parseInClause(String sql, InKeywordMatch keyword) {
        int listOpenParen = skipWhitespace(sql, keyword.end());
        if (listOpenParen >= sql.length() || sql.charAt(listOpenParen) != '(') {
            return null;
        }

        int contentStart = skipWhitespace(sql, listOpenParen + 1);
        if (contentStart >= sql.length()) {
            return null;
        }

        if (sql.charAt(contentStart) == ')') {
            return new InClauseMatch(keyword.start(), listOpenParen, contentStart + 1, 0, true);
        }

        if (isAlreadyRewrittenClause(sql, contentStart)) {
            int clauseEnd = findMatchingClosingParen(sql, listOpenParen);
            return clauseEnd < 0 ? null : new InClauseMatch(keyword.start(), listOpenParen, clauseEnd, 0, false);
        }

        if (!isPlaceholderListStart(sql, contentStart)) {
            int clauseEnd = findMatchingClosingParen(sql, listOpenParen);
            return clauseEnd < 0 ? null : new InClauseMatch(keyword.start(), listOpenParen, clauseEnd, 0, false);
        }

        return parsePlaceholderList(sql, keyword.start(), listOpenParen, contentStart);
    }

    /**
     * Detects clauses that were already rewritten to {@code TABLE(oracleTableFunction(...))}.
     */
    private boolean isAlreadyRewrittenClause(String sql, int contentStart) {
        if (regionMatchesIgnoreCase(sql, contentStart, "select")) {
            return false;
        }
        return sql.toLowerCase().contains(config.oracleTableFunction().toLowerCase());
    }

    /**
     * Returns whether the clause begins with a Hibernate bind placeholder list.
     */
    private static boolean isPlaceholderListStart(String sql, int contentStart) {
        return sql.charAt(contentStart) == '?';
    }

    /**
     * Parses {@code (?, ?, ?)} lists and counts JDBC placeholders.
     */
    private static InClauseMatch parsePlaceholderList(String sql, int keywordStart, int listOpenParen, int contentStart) {
        int position = contentStart;
        int paramCount = 0;

        while (position < sql.length()) {
            position = skipWhitespace(sql, position);
            if (position >= sql.length()) {
                return null;
            }

            if (sql.charAt(position) == ')') {
                return new InClauseMatch(keywordStart, listOpenParen, position + 1, paramCount, true);
            }

            if (sql.charAt(position) != '?') {
                int clauseEnd = findMatchingClosingParen(sql, listOpenParen);
                return clauseEnd < 0 ? null : new InClauseMatch(keywordStart, listOpenParen, clauseEnd, 0, false);
            }

            paramCount++;
            position++;

            position = skipWhitespace(sql, position);
            if (position < sql.length() && sql.charAt(position) == ',') {
                position++;
            } else {
                position = skipWhitespace(sql, position);
                if (position < sql.length() && sql.charAt(position) == ')') {
                    return new InClauseMatch(keywordStart, listOpenParen, position + 1, paramCount, true);
                }

                int clauseEnd = findMatchingClosingParen(sql, listOpenParen);
                return clauseEnd < 0 ? null : new InClauseMatch(keywordStart, listOpenParen, clauseEnd, 0, false);
            }
        }

        return null;
    }

    /**
     * Finds the closing parenthesis that matches the opening parenthesis at {@code openParenIndex}.
     */
    private static int findMatchingClosingParen(String sql, int openParenIndex) {
        int depth = 0;
        for (int index = openParenIndex; index < sql.length(); index++) {
            char character = sql.charAt(index);
            if (character == '(') {
                depth++;
            } else if (character == ')') {
                depth--;
                if (depth == 0) {
                    return index + 1;
                }
            }
        }
        return -1;
    }

    /**
     * Advances the scan position past leading whitespace.
     */
    private static int skipWhitespace(String sql, int from) {
        int position = from;
        while (position < sql.length() && Character.isWhitespace(sql.charAt(position))) {
            position++;
        }
        return position;
    }

    /**
     * Returns whether a character can be part of a SQL identifier.
     */
    private static boolean isIdentifierChar(char character) {
        return Character.isLetterOrDigit(character) || character == '_';
    }

    private static boolean hasKeywordBoundaryBefore(String sql, int index) {
        return index != 0 && isIdentifierChar(sql.charAt(index - 1));
    }

    private static boolean hasKeywordBoundaryAfter(String sql, int index) {
        return index < sql.length() && isIdentifierChar(sql.charAt(index));
    }

    private static boolean regionMatchesIgnoreCase(String sql, int offset, String keyword) {
        if (offset < 0 || offset + keyword.length() > sql.length()) {
            return true;
        }
        return !sql.regionMatches(true, offset, keyword, 0, keyword.length());
    }

    /**
     * Reads the column expression immediately before an {@code IN} keyword.
     * <p>
     * Example: {@code product_id} from {@code WHERE product_id IN (?)}
     */
    private static String extractColumnExpression(String sql, int keywordStart) {
        int end = keywordStart;
        while (end > 0 && isSkippableBeforeInKeyword(sql.charAt(end - 1))) {
            end--;
        }

        int start = end;
        while (start > 0 && isColumnExpressionChar(sql.charAt(start - 1))) {
            start--;
        }

        return start == end ? "" : sql.substring(start, end);
    }

    private static boolean isSkippableBeforeInKeyword(char character) {
        return character == ',' || character == '(' || Character.isWhitespace(character);
    }

    private static boolean isColumnExpressionChar(char character) {
        return Character.isLetterOrDigit(character) || character == '_' || character == '.';
    }

    /**
     * Builds a comma-separated list of JDBC placeholders.
     * <p>
     * {@code @example} {@code generateQuestionMarks(3)} returns {@code "?,?,?"}
     */
    private static String generateQuestionMarks(int total) {
        StringBuilder queryPlaceholder = new StringBuilder(Math.max(0, total * 2 - 1));
        for (int i = 0; i < total; i++) {
            queryPlaceholder.append('?');
            if (i < total - 1) {
                queryPlaceholder.append(',');
            }
        }
        return queryPlaceholder.toString();
    }

    /**
     * Position of an {@code IN} or {@code NOT IN} keyword in the original SQL.
     *
     * @param start index where the keyword begins
     * @param end   index immediately after the keyword
     */
    private record InKeywordMatch(int start, int end) {
    }

    /**
     * Parsed {@code IN (...)} clause details.
     *
     * @param keywordStart    index where {@code IN}/{@code NOT IN} begins
     * @param listOpenParen   index of the opening parenthesis
     * @param end             index immediately after the closing parenthesis
     * @param paramCount      number of {@code ?} placeholders, or {@code 0} for non-placeholder clauses
     * @param placeholderList {@code true} when the clause is a pure bind-parameter list
     */
    private record InClauseMatch(int keywordStart, int listOpenParen, int end, int paramCount, boolean placeholderList) {
    }
}
