-- Switch to the PDB (pluggable database)
ALTER SESSION SET CONTAINER=freepdb1;

-- Grant privileges to OAUTH2_AUTHORIZATION_SERVER_OWNER
GRANT CREATE ANY SYNONYM TO OAUTH2_AUTHORIZATION_SERVER_OWNER;

-- Create the application user
CREATE USER OAUTH2_AUTHORIZATION_SERVER IDENTIFIED BY "password";

-- Grant basic privileges
GRANT CONNECT, RESOURCE TO OAUTH2_AUTHORIZATION_SERVER;

-- ✅ Grant quota on USERS tablespace
ALTER USER OAUTH2_AUTHORIZATION_SERVER QUOTA UNLIMITED ON USERS;
